// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types.ts";

const SUPABASE_URL = "https://qjbdhvntlzjifzhvrkbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqYmRodm50bHpqaWZ6aHZya2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTQ2MDQsImV4cCI6MjA2OTg5MDYwNH0.wyBhJYM4P2Fx3AIAhM3q_GCPC6jmD90-GKXRV4BpiXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
